import './globals.css'
import type { Metadata } from 'next'
import { Maven_Pro } from 'next/font/google'
import NavBar from './views/navbar/navBar'


const font = Maven_Pro({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Core Concept',
  description: 'Generated by Core Concept',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
       <NavBar/>
        {children}
        </body>
    </html>
  )
}
