import './globals.css'
import type { Metadata } from 'next'
import { Maven_Pro } from 'next/font/google'
import Wraper from './shared'
import Navbar from './views/navbar'

const inter = Maven_Pro({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Stuf-Clothes',
  description: 'Generated by Stuff Clothes',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Wraper>
        <Navbar/>
        {children}
        </Wraper>
        </body>
    </html>
  )
}
