import './globals.css'
import type { Metadata } from 'next'
import { Maven_Pro } from 'next/font/google'

const font = Maven_Pro({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Wattoo_Todo',
  description: 'Generated by Wattoo_Todo',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        {children}
      </body>
    </html>
  )
}
