import './globals.css'
import type { Metadata } from 'next'
import { Maven_Pro } from 'next/font/google'
import Navbar from './ingredients/navbar/page'

const inter = Maven_Pro({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Wattoo Clothes Shop',
  description: 'Generated by Wattoo Clothes Shop',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
