import './globals.css'
import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'
import Footer from '@/app/component/footer'

import Container from '@/app/component/ui/containter'
import Navebar from '@/app/component/navbar'

const font = Urbanist({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Wattoo Super Store',
  description: 'Generated by Wattoo Super Store',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Container>
        <Navebar/>
        {children}
        <Footer/>
        </Container>
        </body>
    </html>
  )
}
